language: php

php:
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cd $TRAVIS_BUILD_DIR && cd tests/framework/test && composer install --prefer-source --no-interaction --dev

script: cd $TRAVIS_BUILD_DIR \
  ./vendor/bin/phpunit \
  cd tests/framework/test && ./bin/phpunit \
  cd $TRAVIS_BUILD_DIR \
  cd tests/framework/test && ./bin/phpunit

notifications:
  email: false
